import { AutoGeneratedFields } from "@common/auto-generated-fields";
import { Sku } from "../entities/sku";

export const SkuDataSource = "SkuDataSource";

export interface ISkuDataSource {
  createOne(data: Omit<Sku, AutoGeneratedFields>): Promise<Sku>;
  listByProductId(productId: string): Promise<Sku[]>;
  findOne(skuId: string): Promise<Sku>;
  updateOne(skuId: string, data: Partial<Sku>): Promise<boolean>;
  deleteOne(skuId: string): Promise<boolean>;
  deleteByProduct(productId: string): Promise<boolean>;
}
