import { ISku } from "../entities/Sku";
import { AutoGeneratedFields } from "@utils/auto-generated-fields";

export const SkuService = "SkuService";

export interface ISkuService {
  listByProduct(productId: string): Promise<ISku[]>;
  findOne(productId: string, skuId: string): Promise<ISku>;
  createOne(data: Omit<ISku, AutoGeneratedFields>): Promise<ISku>;
  updateOne(skuId: string, data: Partial<ISku>): Promise<ISku>;
  deleteOne(productId: string, skuId: string): Promise<void>;
}
