import { IsNumber, IsString, IsUrl } from "class-validator";
import { IProduct } from "@core/products/entities/Product";
import { AutoGeneratedFields } from "@utils/auto-generated-fields";
import { Type } from "class-transformer";

export class CreateProductInput implements Omit<IProduct, AutoGeneratedFields> {
  @IsString()
  name: string;

  @IsString()
  description: string;

  @Type(() => Number)
  @IsNumber({ maxDecimalPlaces: 2 })
  price: number;

  @IsUrl()
  imageUrl: string;
}
