import { IProduct } from "@core/products/entities/Product";
import { AutoGeneratedFields } from "@utils/auto-generated-fields";

export class IUpdateProductInput
  implements Partial<Omit<IProduct, AutoGeneratedFields>>
{
  productId: string;

  name?: string;

  description?: string;

  price?: number;
}
