import { ISku } from "@core/skus/entities/Sku";
import { AutoGeneratedFields } from "@utils/auto-generated-fields";
import { Type } from "class-transformer";
import { IsNumber, IsOptional, IsString } from "class-validator";

export class CreateSkuForm
  implements Omit<ISku, AutoGeneratedFields | "productId">
{
  @IsString()
  identifier: string;

  @IsString()
  description: string;

  @IsString()
  @IsOptional()
  ean?: string | undefined;

  @IsNumber({ maxDecimalPlaces: 2 })
  @Type(() => Number)
  @IsOptional()
  price?: number;
}

export const createSkuFormFields: Record<
  keyof CreateSkuForm,
  keyof CreateSkuForm
> = {
  identifier: "identifier",
  description: "description",
  ean: "ean",
  price: "price",
};
