import { AutoGeneratedFields } from "@common/auto-generated-fields";
import { IProductDataSource } from "@core/products/data/product.datasource";
import { IProduct } from "@core/products/entities/product";
import { injectable } from "inversify";

export const MOCK_PRODUCT: IProduct = {
  _id: "mock-id",
  name: "mock name",
  description: "mock description",
  imageUrl: "mock-url.com",
  price: 19.9,
  createdAt: new Date(),
  updatedAt: new Date(),
};

@injectable()
export class ProductMongoDatasource implements IProductDataSource {
  async createOne(
    data: Omit<IProduct, AutoGeneratedFields>
  ): Promise<IProduct> {
    return MOCK_PRODUCT;
  }

  async findOne(productId: string): Promise<IProduct> {
    return MOCK_PRODUCT;
  }

  async list(): Promise<IProduct[]> {
    return [MOCK_PRODUCT];
  }

  async updateOne(
    productId: string,
    data: Partial<IProduct>
  ): Promise<boolean> {
    return true;
  }

  async deleteOne(productId: string): Promise<boolean> {
    return true;
  }
}
