import { AutoGeneratedFields } from "@common/auto-generated-fields";
import { IProduct } from "../entities/product";

export const ProductDataSource = "ProductDataSource";

export interface IProductDataSource {
  findOne(productId: string): Promise<IProduct | null>;
  createOne(data: Omit<IProduct, AutoGeneratedFields>): Promise<IProduct>;
  updateOne(
    productId: string,
    data: Partial<Omit<IProduct, AutoGeneratedFields>>
  ): Promise<boolean>;
  deleteOne(productId: string): Promise<boolean>;
  list(): Promise<IProduct[]>;
}
