import { AutoGeneratedFields } from "@common/auto-generated-fields";
import { IProduct } from "@core/products/entities/product";
import { model, Schema } from "mongoose";

const productSchemaFields: Omit<
  Record<keyof IProduct, any>,
  AutoGeneratedFields
> = {
  name: String,
  description: String,
  price: Number,
  imageUrl: String,
};

export const productSchema = new Schema(productSchemaFields, {
  timestamps: true,
});

export const ProductModel = model("products", productSchema);
