import { ISku } from "@core/skus/entities/Sku";
import { AutoGeneratedFields } from "@utils/auto-generated-fields";

export class CreateSkuInput implements Omit<ISku, AutoGeneratedFields> {
  productId: string;

  identifier: string;

  description: string;

  ean?: string | undefined;

  price?: number;
}
