import { AutoGeneratedFields } from "@common/auto-generated-fields";
import { Sku } from "@core/skus/entities/sku";
import { model, Schema } from "mongoose";

const skuSchemaFields: Omit<Record<keyof Sku, any>, AutoGeneratedFields> = {
  productId: String,
  identifier: String,
  ean: String,
  price: Number,
  description: String,
};

export const skuSchema = new Schema(skuSchemaFields, {
  timestamps: true,
});

export const SkuModel = model("skus", skuSchema);
