import { IProduct } from "@core/products/entities/product";
import { AutoGeneratedFields } from "@common/auto-generated-fields";
import { IsNumber, IsString, IsUrl } from "class-validator";

export class CreateProductInput implements Omit<IProduct, AutoGeneratedFields> {
  @IsString()
  description: string;

  @IsString()
  name: string;

  @IsNumber({ maxDecimalPlaces: 2 })
  price: number;

  @IsUrl()
  imageUrl: string;
}
