import { IsNumber, IsOptional, IsString, Validate } from "class-validator";
import { Sku } from "@core/skus/entities/sku";
import { AutoGeneratedFields } from "@common/auto-generated-fields";
import { IsObjectId } from "@common/validations/is-object-id";

export class CreateSkuInput implements Omit<Sku, AutoGeneratedFields> {
  @Validate(IsObjectId)
  productId: string;

  @IsString()
  description: string;

  @IsString()
  @IsOptional()
  ean?: string;

  @IsString()
  identifier: string;

  @IsNumber({ maxDecimalPlaces: 2 })
  @IsOptional()
  price?: number;
}
